CREATE TABLE COUNTRY (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    CONTINENT VARCHAR(255),
    WIKIPEDIA_LINK VARCHAR(255),
    KEYWORDS VARCHAR(255)
);

CREATE TABLE AIRPORT (
    ID INTEGER PRIMARY KEY,
    AIRPORT_IDENT VARCHAR(255),
    TYPE VARCHAR(255),
    NAME VARCHAR(255),
    ISO_COUNTRY VARCHAR(255)
);

CREATE TABLE RUNWAY (
    ID INTEGER PRIMARY KEY,
    AIRPORT_REF INTEGER,
    LENGTH_FT INTEGER,
    WIDTH_FT INTEGER,
    SURFACE VARCHAR(255),
    LIGHTED BOOLEAN,
    CLOSED BOOLEAN
);

ALTER TABLE AIRPORT ADD CONSTRAINT FK_Airport_Country
FOREIGN KEY (ISO_COUNTRY) REFERENCES COUNTRY(ID);

ALTER TABLE RUNWAY ADD CONSTRAINT FK_Runway_Airport
FOREIGN KEY (AIRPORT_REF) REFERENCES AIRPORT(ID);